import os
dect= os.getcwd()
print(dect)

os.chdir('c:/Users/Study/Desktop/DS-And-Algarithm/Linked_list_project')
print()
create_file_1= open('Linked_list_(append_at_end)_01.py' , 'x') 
create_file_1= open('Linked_list_(append_at_end)_02.py' , 'x')
create_file_1= open('Linked_list_(append_at_end)_03.py' , 'x')
create_file_1= open('Linked_list_(append_at_end)_04.py' , 'x')
create_file_1= open('Linked_list_(append_at_end)_05.py' , 'x')
create_file_1= open('Linked_list_(append_at_end)_06.py' , 'x')
create_file_1= open('Linked_list_(append_at_end)_07.py' , 'x')
create_file_1= open('Linked_list_(append_at_end)_08.py' , 'x')
create_file_1= open('Linked_list_(append_at_end)_09.py' , 'x')
create_file_1= open('Linked_list_(append_at_end)_10.py' , 'x')
create_file_1= open('Linked_list_(append_at_end)_11.py' , 'x')
create_file_1= open('Linked_list_(append_at_end)_12.py' , 'x')
create_file_1= open('Linked_list_(append_at_end)_13.py' , 'x')
create_file_1= open('Linked_list_(append_at_end)_14.py' , 'x')
create_file_1= open('Linked_list_(append_at_end)_15.py' , 'x')
#
create_0file_1= open('Linked_list_insert_value_01.py' , 'x')
create_0file_1= open('Linked_list_insert_value_02.py' , 'x')
create_0file_1= open('Linked_list_insert_value_03.py' , 'x')
create_0file_1= open('Linked_list_insert_value_04.py' , 'x')
create_0file_1= open('Linked_list_insert_value_05.py' , 'x')
create_0file_1= open('Linked_list_insert_value_06.py' , 'x')
create_0file_1= open('Linked_list_insert_value_07.py' , 'x')
create_0file_1= open('Linked_list_insert_value_08.py' , 'x')
create_0file_1= open('Linked_list_insert_value_09.py' , 'x')
create_0file_1= open('Linked_list_insert_value_10.py' , 'x')
create_0file_1= open('Linked_list_insert_value_11.py' , 'x')
create_0file_1= open('Linked_list_insert_value_12.py' , 'x')
create_0file_1= open('Linked_list_insert_value_13.py' , 'x')
create_0file_1= open('Linked_list_insert_value_14.py' , 'x')
create_0file_1= open('Linked_list_insert_value_15.py' , 'x')
#
create_0file_1= open('Linked_list_implemention_01.py' , 'x')
create_0file_1= open('Linked_list_implemention_02.py' , 'x')
create_0file_1= open('Linked_list_implemention_03.py' , 'x')
create_0file_1= open('Linked_list_implemention_04.py' , 'x')
create_0file_1= open('Linked_list_implemention_05.py' , 'x')
